In [2]:
%pip install numpy

import numpy as np


In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(a)

[1 2 3 4 5 6 7 8 9]


In [ ]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
np.all(b<10, axis=0)

array([ True,  True,  True])

In [ ]:
c = np.array([1,2,3,4,5,6,7,8,9,10])
print(c)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
c[0]

1

In [ ]:
c[2]

3

In [ ]:
c[4]

5

In [ ]:
c[6]

7

In [ ]:
c[8]

9

In [ ]:
c[0:-1:3]

array([1, 4, 7])

In [ ]:
d = np.array ([[1,2,3],[4,5,6],[7,8,9]])
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(d[1:10:2])

[[4 5 6]]


In [ ]:
A = np.array([2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24])

AA = A.reshape(2,3,2)

print(AA)

[[[ 2  4]
  [ 6  8]
  [10 12]]

 [[14 16]
  [18 20]
  [22 24]]]


In [ ]:
a = np.arange(1,10).reshape(3,3)
b = np.arange(10,19).reshape(3,3)
c = np.dot(a, b)

print(c)

e = np.sum(c, axis = 0)

print(e)

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]
[603 648 693]


In [4]:
b = np.ones((3,3),dtype=bool)
print(b)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [5]:
c = np.array([1,2,3,4,5,6,7,8,9,10])
d = np.where(c%2 == 0)
print(d)

(array([1, 3, 5, 7, 9]),)


In [6]:
e = np.array([1,2,3,4,5,6,7,8,9,10])
f = e%2 ==1
e[f] = -1
print(e)

[-1  2 -1  4 -1  6 -1  8 -1 10]


In [8]:
g =np.array([1,2,3,4,5,6,7,8])
print(g)
h = g.reshape(2,4)
print(h)

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


In [9]:
i = np.arange(1,10).reshape(3,3)
print(i)
j = np.arange(10,19).reshape(3,3)
print(j)
k = np.dot(i,j)
print(k)
l = np.sum(k,axis = 1)
print(l)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[ 84  90  96]
 [201 216 231]
 [318 342 366]]
[ 270  648 1026]


In [11]:
one = np.ones(3)
two = one + one
three = one * 3

repeat = np.arange(1,4)
print(repeat)
tile = np.tile(repeat,3)
print(tile)

[1 2 3]
[1 2 3 1 2 3 1 2 3]


In [14]:
a = np.arange(1, 6)
b = np.arange(4, 10)

print(a)
print(b)

c = np.setdiff1d(b, a)

print(c)

[1 2 3 4 5]
[4 5 6 7 8 9]
[6 7 8 9]
