<a href="https://colab.research.google.com/github/tahellmiah/D-A-HLT/blob/main/Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
%pip install numpy

import numpy as np


In [35]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(a)

[1 2 3 4 5 6 7 8 9]


In [39]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [57]:
np.all(b<10, axis=0)

array([ True,  True,  True])

In [66]:
c = np.array([1,2,3,4,5,6,7,8,9,10])
print(c)

[ 1  2  3  4  5  6  7  8  9 10]


In [63]:
c[0]

1

In [64]:
c[2]

3

In [65]:
c[4]

5

In [67]:
c[6]

7

In [68]:
c[8]

9

In [92]:
c[0:-1:3]

array([1, 4, 7])

In [8]:
d = np.array ([[1,2,3],[4,5,6],[7,8,9]])
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
print(d[1:10:2])

[[4 5 6]]


In [9]:
A = np.array([2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24])

AA = A.reshape(2,3,2)

print(AA)

[[[ 2  4]
  [ 6  8]
  [10 12]]

 [[14 16]
  [18 20]
  [22 24]]]


In [10]:
a = np.arange(1,10).reshape(3,3)
b = np.arange(10,19).reshape(3,3)
c = np.dot(a, b)

print(c)

e = np.sum(c, axis = 0)

print(e)

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]
[603 648 693]
